# WAF detection module.
# Passively fingerprints firewalls via headers, cookies, and body content.
# When a WAF is detected, core.py enables WAF evasion mode automatically.

import re
from colorama import Fore, Style
from utils.http import get
from utils.severity import finding, INFO

WAF_SIGNATURES = [
    {
        "name"   : "Cloudflare",
        "headers": ["cf-ray", "cf-cache-status", "cf-request-id"],
        "cookies": ["__cflb", "__cfuid", "cf_clearance"],
        "server" : ["cloudflare"],
        "body"   : [r"Cloudflare Ray ID", r"cloudflare\.com/5xx-error-landing"],
    },
    {
        "name"   : "Sucuri",
        "headers": ["x-sucuri-id", "x-sucuri-cache"],
        "cookies": ["sucuri_cloudproxy_uuid"],
        "server" : ["sucuri"],
        "body"   : [r"Sucuri WebSite Firewall", r"sucuri\.net"],
    },
    {
        "name"   : "Wordfence",
        "headers": [],
        "cookies": ["wfvt_", "wordfence_verifiedHuman"],
        "server" : [],
        "body"   : [r"Wordfence", r"generated by Wordfence", r"wfCaptcha"],
    },
    {
        "name"   : "Akamai",
        "headers": ["x-akamai-transformed", "akamai-origin-hop"],
        "cookies": ["ak_bmsc", "bm_sz"],
        "server" : ["akamaighost", "akamai"],
        "body"   : [r"Reference #\d+\.\d+\.\d+\.\d+"],
    },
    {
        "name"   : "Imperva / Incapsula",
        "headers": ["x-iinfo"],
        "cookies": ["incap_ses_", "visid_incap_", "nlbi_"],
        "server" : ["incapsula"],
        "body"   : [r"Incapsula incident ID"],
    },
    {
        "name"   : "ModSecurity",
        "headers": ["x-mod-security-message"],
        "cookies": [],
        "server" : ["mod_security", "modsecurity"],
        "body"   : [r"ModSecurity", r"This error was generated by Mod_Security"],
    },
]


def _score(resp, sig):
    h  = {k.lower(): v.lower() for k, v in resp.headers.items()}
    ck = resp.headers.get("Set-Cookie", "").lower()
    sv = h.get("server", "")
    b  = resp.text[:4000]
    s  = 0
    for hdr in sig["headers"]: s += 3 if hdr in h else 0
    for sv_ in sig["server"]:  s += 3 if sv_ in sv else 0
    for ck_ in sig["cookies"]: s += 2 if ck_ in ck else 0
    for pat in sig["body"]:    s += 2 if re.search(pat, b, re.I) else 0
    return s


def detect(base_url, resp=None):
    resp = resp or get(base_url)
    if resp is None:
        return {"detected": False, "name": None, "confidence": None}

    for sig in WAF_SIGNATURES:
        score = _score(resp, sig)
        if score >= 3:
            return {
                "detected"  : True,
                "name"      : sig["name"],
                "confidence": "high" if score >= 6 else "medium",
            }

    # Try triggering the WAF with a malicious-looking request.
    trigger = get(f"{base_url.rstrip('/')}/?s=<script>alert(1)</script>&id=1+UNION+SELECT+1,2--")
    if trigger and trigger.status_code in (403, 406, 429, 503):
        for sig in WAF_SIGNATURES:
            for pat in sig["body"]:
                if re.search(pat, trigger.text[:4000], re.I):
                    return {"detected": True, "name": sig["name"], "confidence": "medium"}
        return {"detected": True, "name": "Unknown WAF", "confidence": "low"}

    return {"detected": False, "name": None, "confidence": None}


def run(base_url, resp=None):
    print(f"{Fore.CYAN}[*] Checking for WAF / firewall...{Style.RESET_ALL}")
    result   = detect(base_url, resp)
    findings = []

    if result["detected"]:
        name = result["name"]
        conf = result["confidence"]
        print(f"{Fore.YELLOW}[!] WAF detected: {name} (confidence: {conf}){Style.RESET_ALL}")
        print(f"{Fore.YELLOW}    Enabling WAF evasion mode{Style.RESET_ALL}")
        findings.append(finding(
            title       = f"WAF Detected: {name}",
            severity    = INFO,
            description = f"{name} firewall detected (confidence: {conf}).",
            impact      = "Active scanning may be blocked or return false negatives.",
            remediation = "For tester: use --stealth. For client: verify WAF rules are correctly configured.",
            evidence    = f"WAF: {name} | Confidence: {conf}",
        ))
    else:
        print(f"{Fore.GREEN}[+] No WAF detected{Style.RESET_ALL}")

    return result, findings
